n_steps: 10000
ruleset: "stateful"  # 'classic' or 'stateful'
instructions:  # triplet notation (write colour, turn instruction, next state), 
  [            # one state per row, one colour per tuple
    [
      [1, 'R', 0],[1, 'R', 1],
    ],
    [
      [0, 'N', 0],[0, 'N', 1],
    ],
]