CANVAS_SIZE = 8
N_STEPS = 6000
PLOT_MODE = "animate"
CMAP = "Oranges"
RULESET = "RLLR"
ANIMATION_INTERVAL = 1
PADDING_SIZE = 2  # expand in each direction by this amount of cells
SAVE_ANIMATION = False
FRAME_SKIP = 5
